### ISSUE TITLE
Cannot Import to Project

### ISSUE THREAD

**Issue by dozy-programmer** [niendo1/richeditor-android#1]
Hello,

Thanks for taking the time to make this editor better. I am been using Richtext-Editor on a note app for some time. I wanted to see if I can add the improvements you made but I cannot import to my project.

I went to jitpack and put your repo name and this is what I got. 
> No read access to repo

For now, I will just manually import but if this can be resolved, much appreciated.

**Comment by niendo1** [comment]
Hi, dozy-programmer

there was a typo..
this should be correct:
dependencies {
  implementation 'com.github.niendo1:richeditor-android:3.0.0'
}

Thanks!
Peter
