### ISSUE TITLE
Error while Dexing Null Pointer

### ISSUE THREAD

**Issue by Krammig** [niendo1/richeditor-android#3]
Unfortunately I ma getting the following in a project that uses ; 

AGP      7.2.2
Gradle  7.4.2    (tried 7.5.1 also)

AGPBI: {"kind":"error","text":"java.lang.NullPointerException","sources":[{"file":"C:\\tmp\\caches\\transforms-3\\d3255e2016cf8ee818b864bb1d4dc17e\\transformed\\jetified-richeditor-android-3.0.0-runtime.jar"}],"tool":"D8"}

java.lang.NullPointerException

Suggestions would be appreciated. 

Thanks

**Comment by niendo1** [comment]
here I can't really help. I use gradle 8 and higher.

How is the library integrated into the project?

**Comment by niendo1** [comment]
can you try 3.0.2?
