### ISSUE TITLE
Default fontFamily for the editor itself

### ISSUE THREAD

**Issue by Maartinsh** [niendo1/richeditor-android#5]
Hi there,

Thanks for keeping up the forked version of the library.
I saw that there is setFontFamily method that allows you to change font of selected text. Is there anyway to change the default font for editor as well?

If I load "poppins" style using: LoadFont(..), how would I set that to the whole editor as default setting?

**Comment by niendo1** [comment]
Hi,

No, I don't think something like this exists, but you can create a custom.css in or asset folder.
and load. 
   editText.loadCSS("custom.css");

custom.css:
`body {
    font: normal 10px Alita Brush, Verdana, Arial, sans-serif;
}
`
